---
language: ruby
rvm:
- 1.9.3
- 2.0.0
- jruby-19mode
script: bundle exec rake test
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
    - irc.freenode.org#rubyonadhd
env:
  global:
  - secure: bPqqN6twAJeRIpUEGozFIV3+dW2TSRxYQRrQhpzJ6Bx2ZXmk8UWl1O57Scf9/ZrCjo23MSvWKY1Rt1eyncaUVfzr4PjR6GjUwwdE7SPHQFKvGeNLIlJElzcz1ywcX6RU8+6JPYnx3NxR2O5VM8rf7wLwma00nuaDunM5NgKMMdQ=
  - secure: TDOp3nOtFLpGQB4Fn08pmTbD4GmvxQ4hZuqn0CuIL1UarshtfvENMKsLpqTVnz9A+h3eHjB8bTiB994dCPqPyDT6qr/r73UAEvOYnY4lUDYSorIrx/dKGYnKJxr/3WWk+wIOhq00qKfgY4Bws1YYHVZgOczL26l5RLytOYPEyKk=
  - secure: DLNt3OAr07xhgYc7Ju1qVSAeykaz9tOgdG0ya6VVRK7cUmJYzHhMWQErvixgEMnInJoGgdJPe8Bg9NdCrYTxk8gF6sCPAyK2g28NJSiqfkPSMUgS70r/YdcGISjTC+k9H2chB034qN0JDfWYg8tY4l69JB7sCtApBlIfjmK4Aso=
  - secure: QpcuL9NkCD1MP/gJsrnlfnIMV7p9uARHNM5uPnumBYeisd0QCrt1gLBz5fGBpqbMF/peK5cnCVYbjRyteAygKi4sy/CfiA+YqIIPs72Gn2OvZKOWkwvq7UT0oMBhSrF+NGwX7JVSQRgeOqJFpVnkpp5ddW13e27ho/nuOcz3rTs=
