language: ruby
rvm:
  - 1.9.3
script: 'bundle exec rake test'
before_install:
  - gem install bundler
rvm:
  - 1.9.3
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rubyonadhd"